@baseUrl = http://localhost:3333/api

### Add Subscription
POST {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBdWRyYS5LdW56ZTQ2QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzk5ODMyNTAsImV4cCI6MTY3OTk4NDE1MH0.Whgf6rmcxfT3QEJspoJwCbhqWTqxNubt6Vo2WsXVFp8

### Get Notify
GET {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBdWRyYS5LdW56ZTQ2QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzk5ODMyNTAsImV4cCI6MTY3OTk4NDE1MH0.Whgf6rmcxfT3QEJspoJwCbhqWTqxNubt6Vo2WsXVFp8

### Delete Subscription
DELETE {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJMb3JuYTg4QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzkxMTk4MDcsImV4cCI6MTY3OTEyMDcwN30.ydjXk5O5ihMmw2kZzv0gsNOMZitrZ38gQ3ovkNjkC_s
