@baseUrl = http://localhost:3333/api

### Add Subscription
POST {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJMb3JuYTg4QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzkxMTk4MDcsImV4cCI6MTY3OTEyMDcwN30.ydjXk5O5ihMmw2kZzv0gsNOMZitrZ38gQ3ovkNjkC_s

### Get Notify
GET {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJMb3JuYTg4QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzkxMTk4MDcsImV4cCI6MTY3OTEyMDcwN30.ydjXk5O5ihMmw2kZzv0gsNOMZitrZ38gQ3ovkNjkC_s

### Delete Subscription
DELETE {{baseUrl}}/subscription/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJMb3JuYTg4QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzkxMTk4MDcsImV4cCI6MTY3OTEyMDcwN30.ydjXk5O5ihMmw2kZzv0gsNOMZitrZ38gQ3ovkNjkC_s
