version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: fit-friends-postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'fit-friends'
      PGDATA: '/var/lib/postgresql/data/fit-friends'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d secret']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./db:/var/lib/postgresql/data

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fit-friends-fake-smtp
    ports:
      - 5025:5025
      - 8083:5080
