@baseUrl = http://localhost:3333/api

@protocol = HTTP/1.1

### Create Order
POST {{baseUrl}}/order {{protocol}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc1MTE5ODQsImV4cCI6MTY3NzUxMjg4NH0.q6lGMzXXmiSdAYQXmRgAB7izH6MGPZn2q1pBIWfOTSM

{
  "orderType": "тренировка",
  "price": 120,
  "amount": 5,
  "paymentMethod": "visa",
  "purchaseId": 2
}

### Get Orders For Trainer
# ?sortOption=price&sortType=asc
GET {{baseUrl}}/order/trainer {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MTZAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc3NTgzMzAyLCJleHAiOjE2Nzc1ODQyMDJ9.0OuODYktxrcgY6oY2QQcx8_cdh1LgpMs7S6ZAGhaPsw
