@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Register New User Customer
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: multipart/form-data; boundary=Register

--Register
Content-Disposition: form-data; name="name"

John
--Register
Content-Disposition: form-data; name="email"

test1@user.com
--Register
Content-Disposition: form-data; name="password"

secret
--Register
Content-Disposition: form-data; name="role"

пользователь
--Register
Content-Disposition: form-data; name="gender"

мужской
--Register
Content-Disposition: form-data; name="birthDay"

2000-04-12
--Register
Content-Disposition: form-data; name="location"

Пионерская
--Register
Content-Disposition: form-data; name="trainingLevel"

новичок
--Register
Content-Disposition: form-data; name="trainingType"

бокс,бег
--Register
Content-Disposition: form-data; name="trainingTime"

10-30 мин
--Register
Content-Disposition: form-data; name="caloriesAmountToLose"

1200
--Register
Content-Disposition: form-data; name="caloriesAmountToLosePerDay"

1200
--Register
Content-Disposition: form-data; name="isReadyToTraining"

true
--Register
Content-Disposition: form-data; name="avatar"; filename="photo-1.png"
Content-Type: image/png

< ../../../../../test-content/test-img/photo-1.png
--Register--

### Register New User Trainer
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: multipart/form-data; boundary=Register

--Register
Content-Disposition: form-data; name="name"

John
--Register
Content-Disposition: form-data; name="email"

test19@user.com
--Register
Content-Disposition: form-data; name="password"

secret
--Register
Content-Disposition: form-data; name="role"

тренер
--Register
Content-Disposition: form-data; name="gender"

мужской
--Register
Content-Disposition: form-data; name="birthDay"

2000-04-12
--Register
Content-Disposition: form-data; name="location"

Пионерская
--Register
Content-Disposition: form-data; name="trainingLevel"

новичок
--Register
Content-Disposition: form-data; name="trainingType"

кроссфит,бег
--Register
Content-Disposition: form-data; name="resume"

Lorem ipsum dol
--Register
Content-Disposition: form-data; name="isReadyToPersonalTraining"

true
--Register
Content-Disposition: form-data; name="certificate"; filename="certificate-1.pdf"
Content-Type: application/pdf

< ../../../../../test-content/test-img/certificate-1.pdf
--Register
Content-Disposition: form-data; name="avatar"; filename="photo-1.png"
Content-Type: image/png

< ../../../../../test-content/test-img/photo-1.png
--Register--


### Login User
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "Misael_Abbott@yahoo.com",
  "password": "secret"
}

### Refersh Tokens
GET {{baseUrl}}/auth/refresh {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiR2xvcmlhNDRAaG90bWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4MDkzNzU0LCJleHAiOjE2Nzg2OTg1NTR9._hj5eR0fGpcabuEDgcFdzDb8xF2Cc1V_wPgQmkyLXcE


### Logout
GET {{baseUrl}}/auth/logout {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiR2xvcmlhNDRAaG90bWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4MDkzNzY2LCJleHAiOjE2Nzg2OTg1NjZ9.jNSCnJJqUdbqqiVCfvWmLPKdJ_Hde563f_8j6Ym7MY0
