@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Register New User Customer
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: {{contentType}}

{
  "name": "John",
  "email": "test6@user.com",
  "password": "secret",
  "role": "пользователь",
  "gender": "мужской",
  "birthDay": "2000-04-12",
  "location": "Пионерская",
  "trainingLevel": "новичок",
  "trainingType": ["кроссфит", "бег"],
  "trainingTime": "10-30 мин",
  "caloriesAmountToLose": 1200,
  "caloriesAmountToLosePerDay": 1200,
  "isReadyToTraining": true
}

### Register New User Trainer
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: {{contentType}}

{
  "name": "John",
  "email": "test5@user.com",
  "password": "secret",
  "role": "тренер",
  "gender": "мужской",
  "birthDay": "2000-04-12",
  "location": "Пионерская",
  "trainingLevel": "новичок",
  "trainingType": ["кроссфит"],
  "resume": "Lorem ipsum dol",
  "isReadyToPersonalTraining": true
}

### Register New User Trainer Bad Request
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: {{contentType}}

{
  "name": "John1",
  "email": "test4user.com",
  "password": "secet",
  "role": "тренер",
  "gender": "",
  "birthDay": "2000",
  "location": "Fh",
  "trainingLevel": "новичк",
  "trainingType": ["кроссфит", "ab", "bd", "er"],
  "resume": "Lorem",
  "isReadyToPersonalTraining": ""
}

### Login User
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test5@user.com",
  "password": "secret"
}


### Login User Bad Request
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test5user.com",
  "password": "secre"
}

### Login User Forbidden
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test5@user.com",
  "password": "secrett"
}

### Login User Not Found
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test105@user.com",
  "password": "secret"
}


### Refersh Tokens
GET {{baseUrl}}/auth/refresh {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2NzY5MTU5ODcsImV4cCI6MTY3NjkxNjA0N30.UoC9ErBWRuli2eBMXr7EMgqIz1S1KTzcoaNHu6oOJRU


### Logout
GET {{baseUrl}}/auth/logout {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2NzY5MTU5MjYsImV4cCI6MTY3NjkxNTk4Nn0.0KwsORVUyFrT-fSz-9oBUByirpcNGsUtndCLFhBUVZA
