@baseUrl = http://localhost:3333/api

@protocol = HTTP/1.1

### Create Workout Diary Record
POST {{baseUrl}}/workout-diary {{protocol}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBdWRyYS5LdW56ZTQ2QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzk5ODUwNjQsImV4cCI6MTY3OTk4NTk2NH0.X6uGJTFAgqWZGXTPkbaDIzaqHTIRI4rTLF4FcnAYzuw

{
  "workoutId": 1,
  "lostCaloriesAmount": 500,
  "lostTrainingTime": "30-50 мин"
}


### Get Workout Diary Records
GET {{baseUrl}}/workout-diary {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBdWRyYS5LdW56ZTQ2QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzk5ODU5NzgsImV4cCI6MTY3OTk4Njg3OH0.RRb8FJacAn40RepDCnMh-1Dv06ynrsyTunwD_2lApHQ
