@baseUrl = http://localhost:3333/api

### Get Sport Gyms
GET {{baseUrl}}/sport-gym?status=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBdWRyYS5LdW56ZTQ2QGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzk5ODIxMjAsImV4cCI6MTY3OTk4MzAyMH0.HZZ9Nvv2idcVb73Mx0pvwG38fOAoKNzuBx-eQS-I6UI
