@baseUrl = http://localhost:3333/api

@protocol = HTTP/1.1

### Create Food Diary Record
POST {{baseUrl}}/food-diary {{protocol}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0MTlAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4Nzk0NjE2LCJleHAiOjE2Nzg3OTU1MTZ9._jwZ3QFxhw1HGUA-BVj_QV_8zMNUmY2lduZIrU1WBXg

{
  "caloriesAmount": 1200,
  "dateOfMeal": "2023-03-12",
  "typeOfMeal": "завтрак"
}

### Get Food Diary Records
GET {{baseUrl}}/food-diary {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbGlzb24uQWx0ZW53ZXJ0aDY1QGhvdG1haWwuY29tIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MjA4MTA1OSwiZXhwIjoxNjgyMDgxOTU5fQ.gOksvc1r7vNQIwU0CxvzdMzO_4gKLmjGO4dlOpnxv34

### Get Food Diary Record
GET {{baseUrl}}/food-diary/3 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbGlzb24uQWx0ZW53ZXJ0aDY1QGhvdG1haWwuY29tIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTY4MjA4MDA5NCwiZXhwIjoxNjgyMDgwOTk0fQ.VyrgFHDb1QOuLquERfKlG5DkbU9O18zMPv1E3OO7wpo

### Update Food Diary Record
PATCH {{baseUrl}}/food-diary/3 {{protocol}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0MTlAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4NzkzMzgwLCJleHAiOjE2Nzg3OTQyODB9.KW3bEketH68HEDMRhtsyeFucope6bQCJeg9HmQfbUJs

{
  "caloriesAmount": 200
}

### Delete Food Diary Record
DELETE {{baseUrl}}/food-diary/2 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0MTlAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc4NzkzMzgwLCJleHAiOjE2Nzg3OTQyODB9.KW3bEketH68HEDMRhtsyeFucope6bQCJeg9HmQfbUJs


