@baseUrl = http://localhost:3333/api

### Get Notifications
GET {{baseUrl}}/notification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJCYXJyeV9SZW1wZWwzMkB5YWhvby5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc5OTczNzY5LCJleHAiOjE2Nzk5NzQ2Njl9.MsUfRB21lDl934Bjr3Zi7QnvVICZG-cWjIwgJy5wZ9U


### Delete notification
DELETE {{baseUrl}}/notification/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJNaXNhZWxfQWJib3R0QHlhaG9vLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzkxOTk4NjUsImV4cCI6MTY3OTIwMDc2NX0.bRIFj2Yc0xfy-XwqWL-wtwTyZJ_2FCaoSXIedxLOMR8
