@baseUrl = http://localhost:3333/api

@protocol = HTTP/1.1

### Get User
GET {{baseUrl}}/profile/5 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2NzY5NzMxMjcsImV4cCI6MTY3Njk3NDAyN30.lhQ6jSSGinti78wNFe7vmjG4RTS7kOlzMrY-CiQWa5g

### Get Users
# ?limit=2&page=2
# ?sortType=asc
# ?limit=54 Bad Request
GET {{baseUrl}}/profile?limit=1&page=1 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc0MDc3MDMsImV4cCI6MTY3NzQwODYwM30.PVK9BWB8dQbZidHGNI08xhA1ww_cISUXlKTtgHqPOFU

### Update Profile
PATCH  {{baseUrl}}/profile {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MTZAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc3MzQwNTExLCJleHAiOjE2NzczNDE0MTF9.wttw9ywkjCquu8zWJoRd6641q3z77SQIY2UxD2cyvDw
Content-Type: multipart/form-data; boundary=UpdateUser

--UpdateUser
Content-Disposition: form-data; name="name"

Jack
--UpdateUser
Content-Disposition: form-data; name="trainingType"

кроссфит
--UpdateUser
Content-Disposition: form-data; name="trainingType"

бег
--UpdateUser
Content-Disposition: form-data; name="avatar"; filename="photo-1-coach.png"
Content-Type: image/png

< ../../../../../test-content/test-img/photo-1-coach.png
--UpdateUser--

### Add friend
GET {{baseUrl}}/profile/add-friend/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc2NzM4NjcsImV4cCI6MTY3NzY3NDc2N30.V0p65TMCCFr9heDvNxIt4-24NCR9L0tfL2VCwg3yNlQ

### Get Friends
GET {{baseUrl}}/profile/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc2NzM4NjcsImV4cCI6MTY3NzY3NDc2N30.V0p65TMCCFr9heDvNxIt4-24NCR9L0tfL2VCwg3yNlQ
