@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Get User
GET {{baseUrl}}/profile/5 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2NzY5NzMxMjcsImV4cCI6MTY3Njk3NDAyN30.lhQ6jSSGinti78wNFe7vmjG4RTS7kOlzMrY-CiQWa5g

### Get Users
# ?limit=2&page=2
# ?sortType=asc
# ?limit=54 Bad Request
GET {{baseUrl}}/profile {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0ZXN0NkB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzcwNDUyODIsImV4cCI6MTY3NzA0NjE4Mn0.rdW-xtwImYA6HSDIVE5DvoqqkouMSgXBEHmR0yVkR7w

### Update Profile
PATCH  {{baseUrl}}/profile {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0ZXN0NkB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzcwNDk3MTksImV4cCI6MTY3NzA1MDYxOX0.nZNqme6zxwo3IXKBDybts1NpzE2LvBJPXi4vJ0LfUR4

{
  "name": "Jack",
  "trainingType": ["бокс", "пилатес"],
}

### Upload Files
POST {{baseUrl}}/profile/upload-avatar {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ0ZXN0NkB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2NzcxMzM3NTIsImV4cCI6MTY3NzEzNDY1Mn0.maQ285OCwPQEg4SZSCjwWoht0tXGvyVWQUhiY4w7r4M
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="avatar"; filename="photo-1.png"
Content-Type: image/png

< ../../../../../test-img/photo-1.png
--Upload--
# --Upload
# Content-Disposition: form-data; name="certificate"; filename="certificate-1.jpg"
# Content-Type: image/jpeg

# < ../../../../../test-img/certificate-1.jpg

