@baseUrl = http://localhost:3333/api

@protocol = HTTP/1.1

### Get User
GET {{baseUrl}}/profile/2 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MThAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc3OTE5MjE5LCJleHAiOjE2Nzc5MjAxMTl9.sTm0TfeUg5LxN2B99en0F1wit-NTfeBNKPlHa61Nx60

### Get Users
# ?limit=2&page=2
# ?sortType=asc
# ?limit=54 Bad Request
GET {{baseUrl}}/profile?limit=1&page=1 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc0MDc3MDMsImV4cCI6MTY3NzQwODYwM30.PVK9BWB8dQbZidHGNI08xhA1ww_cISUXlKTtgHqPOFU

### Update Profile
PATCH  {{baseUrl}}/profile {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0MThAdXNlci5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiaWF0IjoxNjc3OTI3OTkxLCJleHAiOjE2Nzc5Mjg4OTF9.g5vWoMizMJoHHloSSpkR2UOPtGAPn7hgj6RtNxUcti8
Content-Type: multipart/form-data; boundary=UpdateUser

--UpdateUser
Content-Disposition: form-data; name="name"

Jack
--UpdateUser
Content-Disposition: form-data; name="trainingType"

кроссфит
--UpdateUser
Content-Disposition: form-data; name="trainingType"

бег
--UpdateUser
Content-Disposition: form-data; name="avatar"; filename="photo-1-coach.png"
Content-Type: image/png

< ../../../../../test-content/test-img/photo-1-coach.png
--UpdateUser
Content-Disposition: form-data; name="certificate"; filename="certificate-3.pdf"
Content-Type: application/pdf

< ../../../../../test-content/test-img/certificate-3.pdf
--UpdateUser--

### Add friend
GET {{baseUrl}}/profile/add-friend/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0NUB1c2VyLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2Nzc2NzM4NjcsImV4cCI6MTY3NzY3NDc2N30.V0p65TMCCFr9heDvNxIt4-24NCR9L0tfL2VCwg3yNlQ

### Get Friends
GET {{baseUrl}}/profile/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiTm9ybWEuSGVhdGhjb3RlQHlhaG9vLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2Nzc3ODI2MzUsImV4cCI6MTY3Nzc4MzUzNX0.TMZ4Zar5bXWOuWtP8bHaL08Xgxhghy5YBRibbpRdd0g
